### ISSUE TITLE
I'm becoming code gay

### ISSUE THREAD

**Issue by Annihil** [Ffloriel/a-little-story#1]
Hi good sir,

I trust you're well,

I just wanted to tell you I find the code so beautiful that I started having feelings for it,
to the point that I'm questioning my already fragile sexuality.
Could you produce more "ensure a job for a lifetime" style code in the future so that I don't develop those feelings again?

Thanks my g,

Best regards,

Bap

**Comment by Ffloriel** [comment]
Hi good sir,

I'm well, thank you.

I am sending you this message on the behalf of my code. My code wants to inform you that it doesn't see you in that way. Unfortunately, my code is asexual, it has no sexual interest. But it will want you as a friend. 

Best regards,
Ffloriel

**Comment by contrarian** [comment]
Hi good sir, 

Please inform me if your code's sexuality evolves. I, like our friend Bap, have a keen interest in the matter. 

Cheers,
Don Festive

**Comment by Ffloriel** [comment]
HI good sir,

I am sending you this message on behalf of my code. My code wants to inform you that it will remember you if something changes in that regard. My code is polyamorous and might be open to multiple developers so both you Don Festive and Bap will be considered.

In the meantime, I'm closing this issue. I'll reopen it if my code's sexuality evolves.

Cheers,
Oyster Black
